/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LedgerTest {
    @Test public void testSomeLibraryMethod() {
        Ledger testLedger = new Ledger();
        assertTrue("someLibraryMethod should return 'true'", testLedger.someLibraryMethod());
    }
}
